name: "test"
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, closed]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: github tags play
        run: |
          echo A ${{ github.ref }}
          echo ${{ github.sha }}

      - run: jq --raw-output ${GITHUB_EVENT_PATH}

      - name: "weird import thing"
        run: python3.10 src/aa/bb.py
