name: "test"
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, closed]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Migrate script"
        run: python3.10 src/aa/bb.py
